#!/usr/bin/env python3

# Copyright (C) 2016 Simon Dirmeier
#
# This file is part of rnaiutilities.
#
# rnaiutilities is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rnaiutilities is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rnaiutilities. If not, see <http://www.gnu.org/licenses/>.
#
# @author = 'Simon Dirmeier'
# @email = 'simon.dirmeier@bsse.ethz.ch'

import argparse
import sys
import logging

from rnaiutilities import Controller
from rnaiutilities import Config


def parse_options(args):
    parser = argparse.ArgumentParser(
        description='Parse matlab files of genetic perturbation screens.')
    parser.add_argument('-c',
                        type=str,
                        help='tix config file',
                        required=True,
                        metavar='config')
    opts = parser.parse_args(args)
    return opts.c


def main(args):
    c = Config(parse_options(args))
    logging.basicConfig(level=logging.INFO,
                        format='[%(levelname)-1s/%(processName)-1s/%(name)-1s]: %(message)s')
    # create plate parser object and parse the single plates
    Controller(c).parse()


if __name__ == "__main__":
    main(sys.argv[1:])
