#!/usr/bin/env python3

# Copyright (C) 2016 Simon Dirmeier
#
# This file is part of rnaiutilities.
#
# rnaiutilities is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rnaiutilities is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rnaiutilities. If not, see <http://www.gnu.org/licenses/>.
#
# @author = 'Simon Dirmeier'
# @email = 'simon.dirmeier@bsse.ethz.ch'


import click
import logging

from rnaiutilities import Normalizer

logging.basicConfig(
  format='[%(levelname)-1s/%(processName)-1s/%(name)-1s]: %(message)s')


@click.command()
@click.argument("file", type=str)
@click.argument("normalize", default="zscore", type=str)
def run(file, normalize):
    """
    Normalize RNAi imaging data.
    """
    # TODO: this needs to be changed in case we allow more
    Normalizer(normalize).normalize(file)


if __name__ == "__main__":
    run()
