#!/usr/bin/env python3


import argparse
import sys
import logging

from rnaiutilities import Controller
from rnaiutilities import Config


def parse_options(args):
    parser = argparse.ArgumentParser(
        description='Parse matlab files of genetic perturbation screens.')
    parser.add_argument('-c',
                        type=str,
                        help='tix config file',
                        required=True,
                        metavar='config')
    opts = parser.parse_args(args)
    return opts.c


def main(args):
    c = Config(parse_options(args))
    logging.basicConfig(level=logging.INFO,
                        format='[%(levelname)-1s/%(processName)-1s/%(name)-1s]: %(message)s')
    # create plate parser object and parse the single plates
    Controller(c).parse()


if __name__ == "__main__":
    main(sys.argv[1:])
